name: deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - name: Set default project
        run: gcloud config set core/project joshcarp-installer
      - name: Deploy
        run: |
          gcloud functions deploy whattimeisitrightnow \
                 --entry-point=ServeHTTP \
                 --runtime=go113 \
                 --trigger-http \
                 --allow-unauthenticated
      - name: Set permissions
        run: |-
          gcloud functions add-iam-policy-binding whattimeisitrightnow\
            --member="allUsers" \
            --role="roles/cloudfunctions.invoker"
