name: deploy

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
          project_id: slack-rosterbot
      - name: Deploy
        run: |
          gcloud functions deploy subscribe \
                 --entry-point=SubscribeHandler \
                 --runtime=go113 \
                 --trigger-http \
                 --set-env-vars=GCP_TOPIC=slack,PROJECT_ID=slack-rosterbot \
                 --allow-unauthenticated
      - name: Set permissions
        run: |-
          gcloud functions add-iam-policy-binding subscribe\
            --member="allUsers" \
            --role="roles/cloudfunctions.invoker"
